# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://wuaifx.ga
date_format: "ordinal"
title: 吾爱分享
subtitle: "公众号：吾爱分享"
description: "吾爱分享的个人博客，公众号：吾爱分享"
keywords: 吾爱, wuai, wuaifenxiang, wu ai, 吾爱分享, 吾爱破解, 分享, 分析
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5
repository: wuaifx/website
# 对 css 和 js 资源的 cdn 加速配置
cdn:
    jsdelivr:
        enabled: true
# 组件配置
components:
    # 分享
    share:
        enabled: false
    # 不蒜子访问统计
    busuanzi:
        enabled: true
        start_date: 2020-05-01
# 压缩页面内容
compress_html:
  clippings: all
  comments: ["<!--", "-->"]
# 文章字数统计
word_count:
    enabled: true
# 代码高亮风格，支持的 theme 列表见源文件
highlight_theme: github

# ---------------- #
#      Author      #
# ---------------- #
author: Wu Ai Fen Xiang
organization: 
organization_url: 
github_username: wuaifx
location: BeiJing, China
email: wuaifx@gmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

#   -
#     href: /archives/
#     label: 归档

#   -
#     href: /open-source/
#     label: 开源

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 10
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
plugins:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk

# ---------------- #
#      评论功能    #
# ---------------- #
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: 
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: wuaifx
    repo: blog-comments        
    oauth:
        client_id: dc547669bff958a65fac
        client_secret: 156bc42932214afe44896e8ee6125bc78bc2d8e4
        
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: feibuer
    repo: blog-comments
    clientID: dc547669bff958a65fac
    clientSecret: 156bc42932214afe44896e8ee6125bc78bc2d8e4
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: false
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#      Google      #
# ---------------- #
#google:
#   analytics_id: UA-80669434-1
#   adsense:
#       footer: true
#       sidebar: true 
#       content_header: true
#       content_footer: false
